// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://houcylemgztiueuetfpm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhvdWN5bGVtZ3p0aXVldWV0ZnBtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2NDEzNjgsImV4cCI6MjA2NDIxNzM2OH0.qACv9C2KKrj9t7MYMq68SGJcPG4tZjEUjffEBWA25RM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);